version: "2"

services:

  web:
    image: nginx:latest
    container_name: Nginx
    ports:
      - "80:80"
    volumes:
      - ../:/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/

  php:
    image: herlon214/docker-php7-laravel
    container_name: PHP7
    volumes:
      - ../:/www

  db:
    image: mysql
    container_name: Database
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: classifieds
      MYSQL_USER: classified
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: PHPMyAdmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./sessions:/sessions
